# Generated by Django 3.2.8 on 2021-10-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20211026_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Date_arrived',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
